[sot-hrp2-device]
stack-of-tasks/sot-hrp2 pull request #15
Opened 2017-07-20 16:55 UTC by proyan

* add setNoIntegration function for no integration of control
* move robotState to sot-core device
* map velocity sensor data, if available, to robotVelocity signal

Deals with stack-of-tasks/sot-core#39
Deals with stack-of-tasks/sot-torque-control#3

related to stack-of-tasks/sot-core#40

2017-07-20 17:12 UTC, olivier-stasse requested changes

2017-07-20 17:12 UTC, olivier-stasse commented on src/sot-hrp2-device.cpp
> -  robotState_ ("StackOfTasks(" + RobotName + ")::output(vector)::robotState"),
I am fine with removing robotState_ but you should replace it by something. @andreadelprete and @thomasfla are using it for their estimator. They will not use state.
Could you tell where the encoder values are given ?

2017-07-20 17:12 UTC, olivier-stasse commented on src/sot-hrp2-device.cpp
> +  controlOut["joints"].setValues(controlOut_);
While we are here we should probably change joints by control.

2017-07-20 17:32 UTC, proyan commented on src/sot-hrp2-device.cpp
> -  robotState_ ("StackOfTasks(" + RobotName + ")::output(vector)::robotState"),
The encoder values are currently in the robotState in sot-core device
The current PR should not affect the API. 
As this would be a big change, I did not want to push it here. This would need to be pushed concurrently in all SoT packages.

2017-07-20 17:34 UTC, proyan commented on src/sot-hrp2-device.cpp
> +  controlOut["joints"].setValues(controlOut_);
done with 099af79

2017-07-26 13:24 UTC, andreadelprete commented on src/sot-hrp2-controller.hh
> +  void setNoIntegration(void);
Isn't setNoIntegration redundant?

2017-08-21 08:57 UTC, merged